// End-to-end pipeline with the REAL engine (vendored Stockfish 19 lite, Node child processes):
// setupSelf → first-run sync (newest 300) → analysis → backfill → (cached) re-analysis → training.
// The data is 300 synthetic games of a player 'hero' with planted habitual deviations (generated by
// the benchmark's gen_games.py, seed 20261008; Lichess NDJSON). Slow (about a minute per engine), so
// it only runs with E2E_REAL_ENGINE=1; E2E_POOL sets the number of engines (default 2).
import 'fake-indexeddb/auto';
import { readFileSync } from 'node:fs';
import { afterAll, describe, expect, it } from 'vitest';
import { posFromFen, posKey } from '../core/chess';
import { OpeningBook, type OpeningsJson } from '../core/openings';
import type { AnalysisProgress, Mistake } from '../core/types';
import * as repo from '../db/repo';
import { useTestDb } from '../db/schema';
import { createNodeEngineWorker } from '../engine/nodeWorker';
import { EnginePool } from '../engine/pool';
import { setLichessCooldown } from '../sources/http';
import { FakeLichess } from '../services/__fixtures__/fakes';
import * as store from './store';

const ENABLED = process.env.E2E_REAL_ENGINE === '1';
const POOL_SIZE = Math.max(1, Number(process.env.E2E_POOL) || 2);
/** Just after the newest fixture game (2026-09-30). */
const NOW = Date.UTC(2026, 9, 8, 12);

interface Planted {
  color: 'white' | 'black';
  san: string;
  /** EPD of the position (manifest.json). */
  epd: string;
  uci: string;
  kind: 'hangs_material' | 'offbook';
  /** Games of the 300 in which hero reached the position / played the move. */
  reached: number;
  played: number;
  /** Material the move gives away at once (planted to hang a piece or a pawn). */
  hangs?: 'queen' | 'bishop' | 'pawn';
}

/** manifest.json `planted_deviations`, counted over the newest 300 games (London ...b5 occurs once: not a candidate). */
const PLANTED: Planted[] = [
  { color: 'white', san: 'Qd3', epd: 'rn1qkbnr/pp2pppp/2p5/3pPb2/3P4/8/PPP2PPP/RNBQKBNR w KQkq -', uci: 'd1d3', kind: 'hangs_material', reached: 10, played: 6, hangs: 'queen' },
  { color: 'white', san: 'Qc2', epd: 'r1bqkbnr/pp3ppp/2n1p3/2ppP3/3P4/2P5/PP3PPP/RNBQKBNR w KQkq -', uci: 'd1c2', kind: 'offbook', reached: 7, played: 6 },
  { color: 'white', san: 'Ba6', epd: 'rnbqkbnr/pp3ppp/4p3/2ppP3/3P4/8/PPP2PPP/RNBQKBNR w KQkq -', uci: 'f1a6', kind: 'hangs_material', reached: 22, played: 14, hangs: 'bishop' },
  { color: 'white', san: 'Qe2', epd: 'r1bqk2r/ppp2ppp/2np1n2/2b1p3/2B1P3/2PP1N2/PP3PPP/RNBQK2R w KQkq -', uci: 'd1e2', kind: 'offbook', reached: 21, played: 10 },
  { color: 'white', san: 'Qg4', epd: 'rnbqkbnr/pp2pppp/2p5/3p4/3PP3/8/PPP2PPP/RNBQKBNR w KQkq -', uci: 'd1g4', kind: 'hangs_material', reached: 19, played: 7, hangs: 'queen' },
  { color: 'black', san: 'c5', epd: 'rnbqkb1r/pppppppp/5n2/8/2PP4/8/PP2PPPP/RNBQKBNR b KQkq -', uci: 'c7c5', kind: 'hangs_material', reached: 32, played: 16 },
  { color: 'black', san: 'Ra7', epd: 'rnbqkb1r/1p2pppp/p2p1n2/8/3NP3/2N1B3/PPP2PPP/R2QKB1R b KQkq -', uci: 'a8a7', kind: 'offbook', reached: 12, played: 7 },
  { color: 'black', san: 'b5', epd: 'rnbqkbnr/pp2pppp/3p4/8/3NP3/8/PPP2PPP/RNBQKB1R b KQkq -', uci: 'b7b5', kind: 'hangs_material', reached: 30, played: 13, hangs: 'pawn' },
  { color: 'black', san: 'Kd7', epd: 'rnbqk2r/ppp1ppbp/3p1np1/8/2PPP3/2N2N2/PP3PPP/R1BQKB1R b KQkq -', uci: 'e8d7', kind: 'offbook', reached: 6, played: 4 },
];

const keyOfEpd = (epd: string): string => posKey(posFromFen(`${epd} 0 1`)!);

function fixtureLines(): Record<string, unknown>[] {
  const text = readFileSync(new URL('../services/__fixtures__/hero-300.ndjson', import.meta.url), 'utf8');
  return text
    .split('\n')
    .filter(l => l.trim() !== '')
    .map(l => JSON.parse(l) as Record<string, unknown>);
}

function lastDone(): AnalysisProgress {
  const p = store.analysisProgress.value;
  if (!p || p.phase !== 'done') throw new Error(`analysis did not finish: ${JSON.stringify(p)}`);
  return p;
}

const pool = ENABLED ? new EnginePool({ size: POOL_SIZE, createWorker: () => createNodeEngineWorker(), idleMs: Infinity }) : null;
afterAll(async () => {
  pool?.terminate();
  await store.__resetForTests();
});

describe.skipIf(!ENABLED)('real-engine pipeline (E2E_REAL_ENGINE=1)', () => {
  it('finds the planted habits in 300 synthetic games, then re-analyses from the cache', async () => {
    await store.__resetForTests();
    useTestDb();
    setLichessCooldown(0);
    const book = OpeningBook.fromJson(JSON.parse(readFileSync(new URL('../../public/data/openings.json', import.meta.url), 'utf8')) as OpeningsJson);
    const lichess = new FakeLichess(fixtureLines());
    store.__setTestDeps({ fetchImpl: lichess.fetchImpl, pool: pool!, book, now: () => NOW });

    // ── First run: sync (newest 300), analyse, backfill (nothing older), no second analysis.
    const t0 = performance.now();
    await store.init();
    await store.setupSelf([{ platform: 'lichess', username: 'hero' }]);
    await store.__jobsIdle();
    const firstMs = performance.now() - t0;
    const first = lastDone();
    const self = store.selfProfile.value!;
    expect(self.lastAnalysisAt).toBe(NOW);
    expect(store.games.value).toHaveLength(300);
    expect(first).toMatchObject({ gamesUsed: 300, donePositions: first.totalPositions, cacheHits: 0, engineEvals: first.totalPositions });
    expect(first.error).toBeUndefined();

    const ms = store.mistakes.value;
    const byKey = new Map(ms.map(m => [`${m.posKey}|${m.move}`, m]));
    const found = PLANTED.map(p => ({ p, m: byKey.get(`${keyOfEpd(p.epd)}|${p.uci}`) }));
    const severities = { blunder: 0, mistake: 0, inaccuracy: 0 };
    for (const m of ms) severities[m.severity]++;

    const report = {
      engines: POOL_SIZE,
      wallSeconds: +(firstMs / 1000).toFixed(1),
      games: first.gamesUsed,
      positions: first.totalPositions,
      engineEvals: first.engineEvals,
      cacheHits: first.cacheHits,
      msPerPosition: Math.round(firstMs / first.totalPositions),
      mistakes: ms.length,
      severities,
      lowConfidence: ms.filter(m => m.confidence === 'low').length,
      book: ms.filter(m => m.kind === 'book').length,
      visibleByDefault: store.visibleMistakes.value.length,
      planted: found.map(({ p, m }) =>
        m ? `${p.color} ${p.san} (${p.kind}, ${p.played}/${p.reached}): ${m.severity} −${m.winLoss.toFixed(1)}%, ${m.kind}, count ${m.count}/${m.positionCount}, best ${m.bestMove}` : `${p.color} ${p.san} (${p.kind}): NOT FOUND`,
      ),
    };

    // ── Re-analysis: every position from the cache.
    const t1 = performance.now();
    await store.analyze();
    const secondMs = performance.now() - t1;
    const second = lastDone();
    Object.assign(report, { reanalysis: { wallSeconds: +(secondMs / 1000).toFixed(2), cacheHits: second.cacheHits, engineEvals: second.engineEvals } });

    // ── Training: the top new card, the habit move and the best move.
    const [card] = await store.startSession();
    const habit = card ? await store.submitMove(card, card.mistake.move) : undefined;
    const best = card ? await store.submitMove(card, card.mistake.bestMove) : undefined;
    Object.assign(report, { training: card ? { card: `${card.mistake.color} ${card.mistake.move} (impact ${card.mistake.impact.toFixed(1)})`, habit: habit?.kind, best: best?.kind } : null });
    console.log(`E2E pipeline report\n${JSON.stringify(report, null, 2)}`);

    // Pieces hung outright are found as blunders, with the right count of games.
    for (const { p, m } of found.filter(f => f.p.hangs === 'queen' || f.p.hangs === 'bishop')) {
      expect(m, `${p.san} not found`).toBeDefined();
      expect(m!).toMatchObject({ severity: 'blunder', kind: 'mistake', confidence: 'normal', count: p.played, positionCount: p.reached, color: p.color });
      expect(m!.winLoss).toBeGreaterThanOrEqual(15);
    }
    // A pawn hung in the Najdorf move order is still a clear error.
    const b5 = found.find(f => f.p.hangs === 'pawn')!.m;
    expect(b5, 'Najdorf ...b5 not found').toBeDefined();
    expect(['mistake', 'blunder']).toContain(b5!.severity);
    // Most planted habits surface, and the list is not flooded with noise.
    expect(found.filter(f => f.m).length).toBeGreaterThanOrEqual(6);
    expect(ms.length).toBeGreaterThanOrEqual(found.filter(f => f.m).length);
    expect(ms.length).toBeLessThan(first.totalPositions);
    expect(ms.every((m: Mistake) => m.count >= 2 && m.winLoss >= 5)).toBe(true);

    expect(second).toMatchObject({ cacheHits: second.totalPositions, engineEvals: 0, totalPositions: first.totalPositions });
    expect((await repo.getMistakes(self.id)).length).toBe(ms.length);
    expect(habit).toEqual({ kind: 'habit' });
    expect(best?.kind).toBe('correct');
  }, 15 * 60_000);
});
